def information_data(data):
    print('Первые десять строк датафрейма:')
    display(data.head(10))
    print('Общая информация о датафрейме:')
    display(data.info())
    print('Описание данных:')
    display(data.describe())
    print('Количество пропусков:')
    display(data.isna().sum())
    print('Количество дубликатов:')
    display(data.duplicated().sum())